pipeline {
  agent any
  tools {
        nodejs 'Node 24'  // Name from global config
    }
  stages {
    stage('Build') {
      steps {
        dir('frontend') {
          sh 'npm install'
          sh 'npm run build'
        }
      }
    }
    stage('Deploy') {
      steps {
        sh 'echo "deploying website"'
      }
    }
  }
}
